# jdbc.X
jdbc.driverName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/moviewebsite?allowPublicKeyRetrieval=true&useSSL=false
jdbc.user=root
jdbc.pass=123456789

# hibernate.X
hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=false

# The list of possible options:https://stackoverflow.com/questions/438146/what-are-the-possible-values-of-the-hibernate-hbm2ddl-auto-configuration-and-wha
#hibernate.hbm2ddl.auto=none
hibernate.hbm2ddl.auto=create-drop
#hibernate.hbm2ddl.auto=create
hibernate.cache.use_second_level_cache=false
hibernate.cache.use_query_cache=false
hibernate.enable_lazy_load_no_trains=true

################### JavaMail Configuration ##########################
# unit: time - minutes
email.expiration=15


support.email=cbtongtulenh2001@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.username=cbtongtulenh2001@gmail.com
#spring.mail.password=svowbdywznkefili
spring.mail.password=toiyeuban
spring.mail.properties.mail.transport.protocol=smtps
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.timeout=8000
spring.mail.properties.mail.smtps.write.timeout=8000

# TLS , port 587
#spring.mail.properties.mail.smtp.starttls.enable=true

# SSL, post 465
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
